In [1]:
import torch

from src.transforms.vector.linear.structured_block_upper_triangular import StructuredBlockUpperTriangularVectorTransform
from src.transforms.vector.linear.structured_block_lower_triangular import StructuredBlockLowerTriangularVectorTransform

In [2]:
transform = StructuredBlockUpperTriangularVectorTransform(d=100, r=5, bias=True, random_init=True, efficient_inverse=True)
input_matrix = torch.randn(10, 100)

print("weight_11:", transform.weight_11)
print("weight_12:", transform.weight_12)
print("bias:", transform.bias)

output_matrix, log_abs_det = transform(input_matrix)
print("Output matrix shape:", output_matrix.shape)  # should be [10, 6]
print("Output matrix:", output_matrix)
print("Log absolute determinant:", log_abs_det)

# test inverse
inverse_transform, log_abs_det_inv = transform.inverse(output_matrix)
print("Inverse transform shape:", inverse_transform.shape)  # should be [10, 6]
print("Inverse transform:", inverse_transform)
print("Log absolute determinant (inverse):", log_abs_det_inv)

# test reconstruction
print("Reconstruction error:", torch.norm(input_matrix - inverse_transform).item())

weight_11: Parameter containing:
tensor([[-0.0507, -0.0544, -0.1087, -0.0995,  0.1226],
        [-0.0372,  0.0885,  0.0263,  0.0008,  0.1632],
        [-0.1303,  0.0596, -0.0671, -0.1604, -0.0680],
        [-0.1593, -0.1383,  0.0541, -0.0841, -0.1666],
        [ 0.1645,  0.0647,  0.0111,  0.0878,  0.1516]], requires_grad=True)
weight_12: Parameter containing:
tensor([[ 0.1395, -0.1003, -0.1234,  0.1506,  0.1159,  0.0480, -0.0851,  0.1339,
         -0.0048, -0.1115,  0.1161,  0.1314,  0.1028,  0.0104, -0.0597,  0.0550,
          0.0071, -0.0627,  0.0738,  0.1492, -0.1447, -0.1023,  0.1181, -0.1686,
         -0.0991, -0.0705,  0.1622, -0.0279,  0.1469,  0.0824, -0.1095,  0.1161,
          0.1051, -0.0845, -0.1253, -0.0921,  0.1538,  0.0251, -0.1444,  0.1126,
          0.1092, -0.1702,  0.1329, -0.1156,  0.0563, -0.1057, -0.0984,  0.0190,
          0.0499, -0.0101, -0.0605,  0.0584, -0.0458, -0.0870, -0.0570,  0.1719,
         -0.0525,  0.0215, -0.1231, -0.0160,  0.0498,  0.1548,  0.0367,

In [4]:
transform = StructuredBlockLowerTriangularVectorTransform(d=100, r=10, bias=True, random_init=True, efficient_inverse=True)

print("weight_11:", transform.weight_11)
print("weight_21:", transform.weight_21)
print("bias:", transform.bias)

output_matrix, log_abs_det = transform(input_matrix)
print("Output matrix shape:", output_matrix.shape)  # should be [10, 6]
print("Output matrix:", output_matrix)
print("Log absolute determinant:", log_abs_det)

# test inverse
inverse_transform, log_abs_det_inv = transform.inverse(output_matrix)
print("Inverse transform shape:", inverse_transform.shape)  # should be [10, 6]
print("Inverse transform:", inverse_transform)
print("Log absolute determinant (inverse):", log_abs_det_inv)

# test reconstruction
print("Reconstruction error:", torch.norm(input_matrix - inverse_transform).item())

weight_11: Parameter containing:
tensor([[ 0.0364, -0.0216, -0.0663,  0.3114, -0.3685,  0.4094, -0.5256,  0.3452,
          0.3882,  0.3186],
        [ 0.3298,  0.0951,  0.2563,  0.4057, -0.2298,  0.2333,  0.4990,  0.0243,
          0.1047,  0.3853],
        [ 0.2261, -0.3309,  0.3247, -0.5039,  0.2280,  0.0132, -0.2108, -0.0532,
          0.5416,  0.4398],
        [ 0.2645,  0.3284,  0.4573,  0.3000,  0.0725,  0.1289,  0.3391,  0.0351,
         -0.5045, -0.3723],
        [-0.4892,  0.4585, -0.4052, -0.5000, -0.3204,  0.4517,  0.1525,  0.5211,
          0.4809, -0.3378],
        [-0.4211, -0.1110, -0.5344, -0.2027,  0.0287, -0.4937, -0.1079,  0.1849,
         -0.5264, -0.1481],
        [ 0.2543,  0.0180, -0.2273, -0.3838, -0.2255,  0.4304, -0.0244,  0.1189,
         -0.2112,  0.4986],
        [ 0.3489,  0.4728, -0.1531, -0.4676,  0.2528, -0.3124, -0.0912, -0.4712,
          0.0787, -0.1605],
        [ 0.4670,  0.0740, -0.1474, -0.3948,  0.4828, -0.1064,  0.3647,  0.2195,
         -0.33