In [1]:
import torch

from src.transforms.vector.linear.lower_triangular import LowerTriangularLinearVectorTransform
from src.transforms.vector.linear.upper_triangular import UpperTriangularLinearVectorTransform
from src.transforms.vector.parity.simple_tanh import SimpleTanhParityVectorTransform

In [2]:
utransform = UpperTriangularLinearVectorTransform(3)

print(utransform.weight)

x = torch.randn(5, 3)
y, log_det = utransform.forward(x)
x_reconstructed, inv_log_det = utransform.inverse(y) 
print("Input x:\n", x)
print("Transformed y:\n", y)
print("Reconstructed x:\n", x_reconstructed)

Parameter containing:
tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]], requires_grad=True)
Input x:
 tensor([[-1.7437,  1.2608,  1.0445],
        [-2.0077,  0.4296, -0.0950],
        [-0.1179,  1.1571, -0.3763],
        [ 1.2312, -1.7795,  0.1638],
        [ 0.2389, -0.8952,  0.4120]])
Transformed y:
 tensor([[-1.7437,  1.2608,  1.0445],
        [-2.0077,  0.4296, -0.0950],
        [-0.1179,  1.1571, -0.3763],
        [ 1.2312, -1.7795,  0.1638],
        [ 0.2389, -0.8952,  0.4120]], grad_fn=<AddBackward0>)
Reconstructed x:
 tensor([[-1.7437,  1.2608,  1.0445],
        [-2.0077,  0.4296, -0.0950],
        [-0.1179,  1.1571, -0.3763],
        [ 1.2312, -1.7795,  0.1638],
        [ 0.2389, -0.8952,  0.4120]], grad_fn=<MmBackward0>)


In [3]:
ltransform = LowerTriangularLinearVectorTransform(3)

print(ltransform.weight)
x = torch.randn(5, 3)
y, log_det = ltransform.forward(x)
x_reconstructed, inv_log_det = ltransform.inverse(y) 
print("Input x:\n", x)
print("Transformed y:\n", y)
print("Reconstructed x:\n", x_reconstructed)

Parameter containing:
tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]], requires_grad=True)
Input x:
 tensor([[ 1.0467, -0.8068, -0.0422],
        [-0.6237, -1.5188, -0.3185],
        [ 1.3993, -0.0197, -1.1500],
        [ 1.1976, -0.1318,  0.0613],
        [-1.1658,  0.2520,  0.1830]])
Transformed y:
 tensor([[ 1.0467, -0.8068, -0.0422],
        [-0.6237, -1.5188, -0.3185],
        [ 1.3993, -0.0197, -1.1500],
        [ 1.1976, -0.1318,  0.0613],
        [-1.1658,  0.2520,  0.1830]], grad_fn=<AddBackward0>)
Reconstructed x:
 tensor([[ 1.0467, -0.8068, -0.0422],
        [-0.6237, -1.5188, -0.3185],
        [ 1.3993, -0.0197, -1.1500],
        [ 1.1976, -0.1318,  0.0613],
        [-1.1658,  0.2520,  0.1830]], grad_fn=<MmBackward0>)


In [6]:
stp_transform_1 = SimpleTanhParityVectorTransform(3, parity=0)

y, log_det = stp_transform_1.forward(x)
x_reconstructed, inv_log_det = stp_transform_1.inverse(y)
print("Input x:\n", x)
print("Transformed y:\n", y)
print("Reconstructed x:\n", x_reconstructed)

1
Input x:
 tensor([[ 1.0467, -0.8068, -0.0422],
        [-0.6237, -1.5188, -0.3185],
        [ 1.3993, -0.0197, -1.1500],
        [ 1.1976, -0.1318,  0.0613],
        [-1.1658,  0.2520,  0.1830]])
Transformed y:
 tensor([[ 1.0467, -0.8425, -0.3103],
        [-0.6237, -1.4671, -0.5749],
        [ 1.3993, -0.0813, -1.4074],
        [ 1.1976, -0.1786, -0.2025],
        [-1.1658,  0.3169, -0.0458]], grad_fn=<CopySlices>)
Reconstructed x:
 tensor([[ 1.0467, -0.8068, -0.0422],
        [-0.6237, -1.5188, -0.3185],
        [ 1.3993, -0.0197, -1.1500],
        [ 1.1976, -0.1318,  0.0613],
        [-1.1658,  0.2520,  0.1830]], grad_fn=<CopySlices>)
